### ISSUE TITLE
Missing schema 30

### ISSUE THREAD

**Issue by Flohack74** [stek29/tl-schema#1]
Hi,

if it is not too much effort could you please upload schema 30? As your files seem to be incremental would be nice to see whats in there :)

thanks!

**Comment by stek29** [comment]
I wasn't able to find it, seems like TG skipped it. I'm planning to reverse older versions of iOS and android apps to look for missing layers (69 is missing too btw)

**Comment by Flohack74** [comment]
Ok would be nice if you can hack into that :)

**Comment by stek29** [comment]
@Flohack74 I suggest you just skip those missing layers since they've not been used in official apps.
I wasn't able to find a good archive of older versions, and tbh I'm too lazy to parse reverse engineered smali/java code or mess with iOS app which is really hard.

**Comment by Flohack74** [comment]
I agree, just running test build with 29=>31 changes and seem to work ;) thx!
